### ISSUE TITLE
autotools

### ISSUE THREAD

**Issue by sjsonucool** [rb-anssi/lightweight-crypto-lib#1]
Can you help with the usage of autotools in order to run it? I have configured and installed autotools but when I am trying to configure or make this project, it is not working.
![screenshot from 2017-01-04 00 21 56](https://cloud.githubusercontent.com/assets/23055836/21619019/dd34d978-d213-11e6-9ff7-dcf9a08b90cd.png)

**Comment by rben-dev** [comment]
Dear Sonu,

You have to run "./autogen.sh" in order to produce the configure file (and then run "./configure" with your options).

Regards.

**Comment by sjsonucool** [comment]
Dear Ryad,

Thanks for the info. But the makefile compilation still gives the same error and undefined references to dlsym, dlopen, dlerror in functions load_ciphers_symbols and main, and test run from bin (./check_all_ciphers) isn't working. Can you give some ideas to overcome these problems? Also how can I fall back to to non AVX implementations because my cpu doesn't support it.

**Comment by rben-dev** [comment]
Dear Sonu,

1) Regarding the dlXXX symbol errors, could you please try to use in your prompt the following command line:
$ gcc -DTABLE -DVPERM -DBITSLICE -DAVX -DBASHCOLORS -DTEST_VECTORS -DMEASURE_PERF -DLED64 -DLED128 -DPRESENT80 -DPRESENT128 -DPiccolo80 -DPiccolo128 -DTHREAD_SAFE -Wall -Wextra -Wpointer-arith -Wcast-align -Wredundant-decls -Wnested-externs -Winline -Wuninitialized -O3 -I src src/common/check_all.c -o bin/check_all_ciphers -ldl

=> (please notice that the -ldl position is changed compared to the Makefile, and if this works then the issue could be related to the gcc version: if this is the case I will update the Makefiles and make a new commit).

2) Regarding the AVX option, you can change this by using the configure options as stated in the README.md file:
$ ./configure --without-avx
==> This forces no AVX
However, SSSE3 and AVX should be automatically detected when running ./configure since a runtime CPU check is executed. Please be sure to run:
$ ./autoclean.sh
$ ./autogen.sh
$ ./configure
and check the result of the configuration summary, on my machine this gives:
###     Detected CPU: x86 64-bit        ###
###     Detected CPU: SSSE3 and AVX     ###

Regards,

**Comment by sjsonucool** [comment]
Dear Ryad,

Thanks for the help.. Yes it was the issue related to gcc version because ['gcc -DTABLE -DVPERM -DBITSLICE -DAVX -DBASHCOLORS -DTEST_VECTORS -DMEASURE_PERF -DLED64 -DLED128 -DPRESENT80 -DPRESENT128 -DPiccolo80 -DPiccolo128 -DTHREAD_SAFE -Wall -Wextra -Wpointer-arith -Wcast-align -Wredundant-decls -Wnested-externs -Winline -Wuninitialized -O3 -I src src/common/check_all.c -o bin/check_all_ciphers -ldl'] is working. But the test run is still throwing an unknown error---> 

`sonu@sonu-System-Product-Name:~/lightweight-crypto-lib-master/bin$ ./check_all_ciphers
Unknown error: don't know what to do with the catched SIGILL!
sonu@sonu-System-Product-Name:~/lightweight-crypto-lib-master/bin$ ./check_all_ciphers -h
Unknown error: don't know what to do with the catched SIGILL!`

**Comment by rben-dev** [comment]
Dear Sonu,

1) The Makefile.in and Makefile.default have been corrected in the last commits to deal with the gcc issue.
2) The SIGILL error you are getting is related to the non-AVX CPU you have: the .so library you have compiled is for AVX, which produces a so called "illegal instruction" exception when running. Please proceed with a proper ./autoclean.sh ./autogen.sh and ./configure after a "git pull" to get the last commits. The ./configure *should detect* that your CPU does not support AVX and adapt the Makefile => if this is not the case, please report it!

Regards,

**Comment by sjsonucool** [comment]
Dear Ryad,

It seems to adapt the makefile now according to my cpu features but the SIGILL error doesn't seem to go away after test run **./check_all_ciphers** :(

**Comment by rben-dev** [comment]
Dear Sonu,

Can you send me:
- The result of the configure log as well as its summary.
- The content of the /proc/cpuinfo file.

Thanks,

**Comment by sjsonucool** [comment]
Dear Ryad,

I sent the files and summary in your email provided here. Thank you.

**Comment by rben-dev** [comment]
Dear Sonu,

This line is weird:
Using AVX                               :   YES

=> this is not normal, the configure should not have detected it.

Can we try two things:
1)- Please force non-AVX with a "./configure --without-avx", and try to run the tests.
2)- Can you compile and run the check.c file I am sending on your private email, and give me its output?

Regards,

**Comment by sjsonucool** [comment]
Dear Ryad,

The test run seems to work with `./configure --without-avx`.
The summary says yes for avx and yes that's weird. But while configuring it also says the same thing which is given here as output of check.c

The output of the check.c file is as follows
`sonu@sonu-System-Product-Name:~$ gcc check.c -o check
sonu@sonu-System-Product-Name:~$ gcc check.c -o check
sonu@sonu-System-Product-Name:~$ gcc check.c
sonu@sonu-System-Product-Name:~$ ./check
Sorry, but your CPU does not seem to support AVX instructions!
You will have to fall back on non AVX implementations (vperm without AVX, bitslice or table based) ...
sonu@sonu-System-Product-Name:~$ `

Thank you!!

**Comment by rben-dev** [comment]
Dear Sonu,

Thanks for the feedback, glad to see that this works when forcing AVX off. I suspect that there might be some issue with the configure file when detecting your CPU. Can you please send me the prompt output (not the configure.out) of the execution of ./configure?

If you don't mind, I might send you a modified configure.ac (and maybe modified .c/.h files) to try to track the problem on your system! Thanks in advance for your help.

Regards,

**Comment by sjsonucool** [comment]
Dear Ryad,

The Prompt output of ./configure

`
sonu@sonu-System-Product-Name:~/lightweight-crypto-lib-master$ ./configure
checking for make... make
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
configure: ---> Your CPU is in 64-bit mode
Sorry, but your CPU does not seem to support AVX instructions!
You will have to fall back on non AVX implementations (vperm without AVX, bitslice or table based) ...
configure: Using table based functions
configure: Using vperm functions
configure: Using bitslice functions
configure: creating ./config.status
config.status: creating .//Makefile
config.status: creating Makefile
###########################################
###               SUMMARY               ###
###########################################
###     Detected CPU: x86 64-bit        ###
table                                   :   YES
vperm                                   :   YES
bitslice                                :   YES
LED64                                   :   YES
LED128                                  :   YES
PRESENT80                               :   YES
PRESENT128                              :   YES
Piccolo80                               :   YES
Piccolo128                              :   YES
Using SSSE                              :   YES
Using AVX                               :   YES
Using thread-safe functions             :   YES
Compiling for architecture (detected)   :   64-bit
sonu@sonu-System-Product-Name:~/lightweight-crypto-lib-master$
` 

------------------------------------------------------------------------------
And yes you can send me the updated files for sure so that I can give you updates in order to track the problem.

Thank you.

**Comment by rben-dev** [comment]
Dear Sonu,

I think that I might have detected where is the issue: I have updated some files in the last commit. Can you do a "git pull", and then ./autoclean.sh, ./autogen.sh, ./configure and make?

Thanks in advance for your help,
Regards,

**Comment by sjsonucool** [comment]
Dear Ryad,

I used the updated zip. But seems like it's still not adapting properly...

sonu@sonu-System-Product-Name:~/lightweight-crypto-lib-master$ ./configure
checking for make... make
checking for gcc... gcc
checking for C compiler default output file name... a.out
checking whether the C compiler works... yes
checking whether we are cross compiling... no
checking for suffix of executables... 
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
configure: ---> Your CPU is in 64-bit mode
Sorry, but your CPU does not seem to support AVX instructions!
You will have to fall back on non AVX implementations (vperm without AVX, bitslice or table based) ...
configure: ---> Your CPU supports SSSE3 but not AVX
configure: Using table based functions
configure: Using vperm functions
configure: Using bitslice functions
configure: creating ./config.status
config.status: creating .//Makefile
config.status: creating Makefile
###########################################
###               SUMMARY               ###
###########################################
###     Detected CPU: x86 64-bit        ###
###     Detected CPU: SSSE3, no AVX     ###
###########################################
table                                   :   YES
vperm                                   :   YES
bitslice                                :   YES
LED64                                   :   YES
LED128                                  :   YES
PRESENT80                               :   YES
PRESENT128                              :   YES
Piccolo80                               :   YES
Piccolo128                              :   YES
Using SSSE                              :   YES
Using AVX                               :   YES
Using thread-safe functions             :   YES
Compiling for architecture (detected)   :   64-bit

In the summary headline, it is showing no AVX but the Using AVS is set to yes. The test run from bin throws the SIGILL exception again. However, Configuring without avx is still working good.

**Comment by rben-dev** [comment]
Dear Sonu,

Thanks for this feedback. I have fixed the configure.ac: can you check it again (through the same ./autoclean.sh ... process).

Thanks!
Regards,

**Comment by sjsonucool** [comment]
Dear Ryad,

It is working just perfect now. Thank you so much for the help and patience!! :)

**Comment by rben-dev** [comment]
Dear Sonu,

This is good news! Thank you for your help and feedback.

Regards,
