### ISSUE TITLE
why have two bitslice in Appedix B Result tables？

### ISSUE THREAD

**Issue by zzszhao** [rb-anssi/lightweight-crypto-lib#2]
why have two bitslice in Appedix B Result tables？

**Comment by rben-dev** [comment]
Hi zzszhao,

The two bitslice results correspond to 16-blocks and 32-blocks parallel bitslicing computations as explained in section 4 (see also Fig. 9 to 11 for the associated packing strategies).

Regards,

**Comment by zzszhao** [comment]
Dear Ryad,
i can‘t believe your reply. Because i thought you have forgot it.

Best wishes!
